services:
  kafka-broker:
    image: aurelienwaite/kafka-broker:latest
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,CONTROLLER://kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka-broker", "9092"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    attach: false

  aggregator-kafka:
    image: aurelienwaite/aggregator-kafka:latest
    container_name: aggregator-kafka
    depends_on:
      kafka-broker:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 3s
    attach: false

  aggregator-broker:
    image: aurelienwaite/aggregator-redis:latest
    container_name: aggregator-redis
    depends_on:
      redis:
        condition: service_healthy
